RDK:
  eccentricity: 15
  dot_size: 0.5
  width: 10
  density: 0.001
  speed: 0.18
  position_jitter: 0  # dva
  duration: 800  # ms
  n_dots: 40
  field_size: 10  # dva
  dot_life: 80
  side: left
# ---------------------------------------
Fixation:
  size: 0.4
  fill_color: [1, -1, -1]
  line_color: [1, 1, 1]
  line_width: 3
# ---------------------------------------
FixationImage:
  width: 3  # dva
# ---------------------------------------
Calibration:
  num_tagets: 5
  target_size: 100
# ---------------------------------------
Noise:
  eccentricity: 15
  dot_size: 0.5
  width: 10
  density: 0.001
  speed: 0.18
  position_jitter: 0  # dva
  n_dots: 40
  field_size: 10  # dva
  dot_life: 80
  side: left
# ---------------------------------------
Gabor:
  eccentricity: 15  # dva
  sigma: 2  # dva
  size: 12  # dva
  contrast: 0.8  # proportion (0-1)
  opacity: 0.5
  position_jitter: 0  # dva
  orientation: 60  # degrees
  texture: sqr
  side: left