RDK:
  eccentricity: 15
  dot_size: 0.5
  width: 10
  density: 0.001
  speed: 0.8
  duration: 0.5  # ms
  position_jitter: 3
  side: left
# ---------------------------------------
Fixation:
  size: 0.5
  color: [1, 1, 1]
# ---------------------------------------
Calibration:
  num_tagets: 5
  target_size: 100
