RDK:
  eccentricity: 22
  dot_size: 0.7
  width: 10
  density: 0.001
  speed: 0.18
  duration: 0.5  # s
  position_jitter: 3
  n_dots: 40
  field_size: 20  # dva
  dot_life: 80
  side: left
# ---------------------------------------
Fixation:
  size: 0.5
  color: [1, 1, 1]
# ---------------------------------------
Calibration:
  num_tagets: 5
  target_size: 100
