fixation_tolerance: 3  # dva
fixation_timeout: 5000  # ms
fixation_hold: 200  # ms
fixation_duration: 350  # ms
fixation_jitter: 100  # ms
fixation_blink_period: 300  # ms
saccade_tolerance: 3  # dva
saccade_initiation_duration: 500  # ms
saccade_duration: 100  # ms
max_rdk_duration: 800  # ms
rdk_speeds: [15, 25]  # dva/s
coherence_levels: [0.33, 1]  # proportion
inter_trial_interval: 300  # ms
reward_amount: 0.25  # ml
directions: [90, 270]  # degrees (90=up, 270=down)
n_trials_per_condition: 20